# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './window.ui'
#
# Created: Fri Dec  9 23:06:22 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 641)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Data_Tabs = QtGui.QTabWidget(self.centralwidget)
        self.Data_Tabs.setObjectName("Data_Tabs")
        self.Proton_tab = QtGui.QWidget()
        self.Proton_tab.setObjectName("Proton_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.Proton_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.Proton_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_frequency = QtGui.QLineEdit(self.Proton_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_frequency.setSizePolicy(sizePolicy)
        self.lineEdit_frequency.setObjectName("lineEdit_frequency")
        self.horizontalLayout.addWidget(self.lineEdit_frequency)
        self.label_5 = QtGui.QLabel(self.Proton_tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_protonsolvent = QtGui.QComboBox(self.Proton_tab)
        self.comboBox_protonsolvent.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_protonsolvent.setObjectName("comboBox_protonsolvent")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.comboBox_protonsolvent.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_protonsolvent)
        spacerItem = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_proton = QtGui.QTableWidget(self.Proton_tab)
        self.tableWidget_proton.setMinimumSize(QtCore.QSize(280, 0))
        self.tableWidget_proton.setObjectName("tableWidget_proton")
        self.tableWidget_proton.setColumnCount(5)
        self.tableWidget_proton.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_proton.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_proton.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_proton.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_proton.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_proton.setHorizontalHeaderItem(4, item)
        self.tableWidget_proton.horizontalHeader().setDefaultSectionSize(87)
        self.tableWidget_proton.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_proton.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget_proton)
        self.Data_Tabs.addTab(self.Proton_tab, "")
        self.Carbon_tab = QtGui.QWidget()
        self.Carbon_tab.setObjectName("Carbon_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Carbon_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_6 = QtGui.QLabel(self.Carbon_tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_carbonfrequency = QtGui.QLineEdit(self.Carbon_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_carbonfrequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_carbonfrequency.setSizePolicy(sizePolicy)
        self.lineEdit_carbonfrequency.setObjectName("lineEdit_carbonfrequency")
        self.horizontalLayout_4.addWidget(self.lineEdit_carbonfrequency)
        self.label_7 = QtGui.QLabel(self.Carbon_tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.comboBox_carbonsolvent = QtGui.QComboBox(self.Carbon_tab)
        self.comboBox_carbonsolvent.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_carbonsolvent.setObjectName("comboBox_carbonsolvent")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.comboBox_carbonsolvent.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_carbonsolvent)
        spacerItem2 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.tableWidget_carbon = QtGui.QTableWidget(self.Carbon_tab)
        self.tableWidget_carbon.setMinimumSize(QtCore.QSize(280, 0))
        self.tableWidget_carbon.setObjectName("tableWidget_carbon")
        self.tableWidget_carbon.setColumnCount(2)
        self.tableWidget_carbon.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_carbon.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_carbon.setHorizontalHeaderItem(1, item)
        self.tableWidget_carbon.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_carbon.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_5.addWidget(self.tableWidget_carbon)
        spacerItem4 = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.Data_Tabs.addTab(self.Carbon_tab, "")
        self.IR_tab = QtGui.QWidget()
        self.IR_tab.setObjectName("IR_tab")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.IR_tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.tableWidget_IR = QtGui.QTableWidget(self.IR_tab)
        self.tableWidget_IR.setMinimumSize(QtCore.QSize(280, 0))
        self.tableWidget_IR.setObjectName("tableWidget_IR")
        self.tableWidget_IR.setColumnCount(2)
        self.tableWidget_IR.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_IR.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_IR.setHorizontalHeaderItem(1, item)
        self.tableWidget_IR.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_IR.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.tableWidget_IR)
        spacerItem6 = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.Data_Tabs.addTab(self.IR_tab, "")
        self.AD_tab = QtGui.QWidget()
        self.AD_tab.setObjectName("AD_tab")
        self.formLayout = QtGui.QFormLayout(self.AD_tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_specificrotation = QtGui.QLabel(self.AD_tab)
        self.label_specificrotation.setObjectName("label_specificrotation")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_specificrotation)
        self.lineEdit_specificrotation = QtGui.QLineEdit(self.AD_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_specificrotation.sizePolicy().hasHeightForWidth())
        self.lineEdit_specificrotation.setSizePolicy(sizePolicy)
        self.lineEdit_specificrotation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_specificrotation.setObjectName("lineEdit_specificrotation")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_specificrotation)
        self.label_concentration = QtGui.QLabel(self.AD_tab)
        self.label_concentration.setObjectName("label_concentration")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_concentration)
        self.lineEdit_concentration = QtGui.QLineEdit(self.AD_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_concentration.sizePolicy().hasHeightForWidth())
        self.lineEdit_concentration.setSizePolicy(sizePolicy)
        self.lineEdit_concentration.setObjectName("lineEdit_concentration")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_concentration)
        self.label_solvent = QtGui.QLabel(self.AD_tab)
        self.label_solvent.setObjectName("label_solvent")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_solvent)
        self.lineEdit_solvent = QtGui.QLineEdit(self.AD_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_solvent.sizePolicy().hasHeightForWidth())
        self.lineEdit_solvent.setSizePolicy(sizePolicy)
        self.lineEdit_solvent.setObjectName("lineEdit_solvent")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_solvent)
        self.Data_Tabs.addTab(self.AD_tab, "")
        self.horizontalLayout_2.addWidget(self.Data_Tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        self.menuCompile = QtGui.QMenu(self.menubar)
        self.menuCompile.setObjectName("menuCompile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/filenew.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/document_open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/document_save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/document_save_as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionCompile = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/compfile.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCompile.setIcon(icon4)
        self.actionCompile.setObjectName("actionCompile")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/contents.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/document_properties.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/application_exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_Row = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/images/edit_add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Row.setIcon(icon8)
        self.actionAdd_Row.setObjectName("actionAdd_Row")
        self.actionRemove_Row = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/edit_delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Row.setIcon(icon9)
        self.actionRemove_Row.setObjectName("actionRemove_Row")
        self.menuCompile.addAction(self.actionCompile)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_Row)
        self.menuEdit.addAction(self.actionRemove_Row)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCompile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionCompile)
        self.toolBar.addAction(self.actionAdd_Row)
        self.toolBar.addAction(self.actionRemove_Row)
        self.label_specificrotation.setBuddy(self.lineEdit_specificrotation)
        self.label_concentration.setBuddy(self.lineEdit_concentration)
        self.label_solvent.setBuddy(self.lineEdit_solvent)

        self.retranslateUi(MainWindow)
        self.Data_Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Experimental Data to Latex (expdata2tex)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "MHz in", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(0, QtGui.QApplication.translate("MainWindow", "Chloroform-d1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(1, QtGui.QApplication.translate("MainWindow", "Acetic Acid-d4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(2, QtGui.QApplication.translate("MainWindow", "Acetone-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(3, QtGui.QApplication.translate("MainWindow", "Acetonitrile-d3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(4, QtGui.QApplication.translate("MainWindow", "Benzene-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(5, QtGui.QApplication.translate("MainWindow", "DCM-d2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(6, QtGui.QApplication.translate("MainWindow", "DMF-d7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(7, QtGui.QApplication.translate("MainWindow", "DMSO-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(8, QtGui.QApplication.translate("MainWindow", "Ethanol-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(9, QtGui.QApplication.translate("MainWindow", "Methanol-d4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(10, QtGui.QApplication.translate("MainWindow", "Nitromethane-d3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(11, QtGui.QApplication.translate("MainWindow", "Pyridine-d5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(12, QtGui.QApplication.translate("MainWindow", "TFA-d1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(13, QtGui.QApplication.translate("MainWindow", "THF-d8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(14, QtGui.QApplication.translate("MainWindow", "Toluene-d8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(15, QtGui.QApplication.translate("MainWindow", "Trifluoroethanol-d3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_protonsolvent.setItemText(16, QtGui.QApplication.translate("MainWindow", "Water-d2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_proton.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_proton.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Protons", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_proton.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Multiplicity", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_proton.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Coupling (J)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_proton.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Identity", None, QtGui.QApplication.UnicodeUTF8))
        self.Data_Tabs.setTabText(self.Data_Tabs.indexOf(self.Proton_tab), QtGui.QApplication.translate("MainWindow", "Proton NMR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "MHz in", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(0, QtGui.QApplication.translate("MainWindow", "Chloroform-d1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(1, QtGui.QApplication.translate("MainWindow", "Acetic Acid-d4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(2, QtGui.QApplication.translate("MainWindow", "Acetone-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(3, QtGui.QApplication.translate("MainWindow", "Acetonitrile-d3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(4, QtGui.QApplication.translate("MainWindow", "Benzene-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(5, QtGui.QApplication.translate("MainWindow", "DCM-d2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(6, QtGui.QApplication.translate("MainWindow", "DMF-d7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(7, QtGui.QApplication.translate("MainWindow", "DMSO-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(8, QtGui.QApplication.translate("MainWindow", "Ethanol-d6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(9, QtGui.QApplication.translate("MainWindow", "Methanol-d4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(10, QtGui.QApplication.translate("MainWindow", "Nitromethane-d3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(11, QtGui.QApplication.translate("MainWindow", "Pyridine-d5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(12, QtGui.QApplication.translate("MainWindow", "TFA-d1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(13, QtGui.QApplication.translate("MainWindow", "THF-d8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(14, QtGui.QApplication.translate("MainWindow", "Toluene-d8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(15, QtGui.QApplication.translate("MainWindow", "Trifluoroethanol-d3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_carbonsolvent.setItemText(16, QtGui.QApplication.translate("MainWindow", "Water-d2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_carbon.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_carbon.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Identity", None, QtGui.QApplication.UnicodeUTF8))
        self.Data_Tabs.setTabText(self.Data_Tabs.indexOf(self.Carbon_tab), QtGui.QApplication.translate("MainWindow", "Carbon NMR", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_IR.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_IR.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Strength", None, QtGui.QApplication.UnicodeUTF8))
        self.Data_Tabs.setTabText(self.Data_Tabs.indexOf(self.IR_tab), QtGui.QApplication.translate("MainWindow", "IR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_specificrotation.setText(QtGui.QApplication.translate("MainWindow", "Specific Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_concentration.setText(QtGui.QApplication.translate("MainWindow", "Concentration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent.setText(QtGui.QApplication.translate("MainWindow", "Solvent", None, QtGui.QApplication.UnicodeUTF8))
        self.Data_Tabs.setTabText(self.Data_Tabs.indexOf(self.AD_tab), QtGui.QApplication.translate("MainWindow", "Specific Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCompile.setTitle(QtGui.QApplication.translate("MainWindow", "Compile", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompile.setText(QtGui.QApplication.translate("MainWindow", "&Compile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Row.setText(QtGui.QApplication.translate("MainWindow", "&Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Row.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Row.setText(QtGui.QApplication.translate("MainWindow", "&Remove Row", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
